#!/usr/bin/env bash
set -e

PATTERNS=(
  "Claude"
  "Anthropic"
  "GPT"
  "AI-generated"
  "AI generated"
  "generated by AI"
  "Copilot"
  "Co-Authored-By: Claude"
)

FOUND=0

for pattern in "${PATTERNS[@]}"; do
  if grep -r --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
       --include="*.md" --include="*.json" \
       -l "$pattern" src/ docs/ scripts/ 2>/dev/null | grep -v node_modules; then
    echo "ERROR: Found prohibited string: '$pattern'"
    FOUND=1
  fi
done

if [ $FOUND -eq 1 ]; then
  echo "Sanitize check FAILED. Remove all AI attribution strings before shipping."
  exit 1
fi

echo "Sanitize check passed."
exit 0
